### ISSUE TITLE
Extend scatterSeries to allow to draw lines

### ISSUE THREAD

**Issue by targos** [zakodium/react-plot#50] opened 2020-12-16 10:54 UTC
- Idea for ScatterSeries: ~`colorScale` callback that receives the data point and returns a color~.
- Each "style" prop can be either a constant value or a callback that receives the current point, index, and array and must return the value.
- Should we have some API for LineSeries? If we do, how to support interpolation between points? -> draw small segments with their own color

**Comment by targos** [comment] 2020-12-16 10:54
Example with Excel: color depends on Y value

![image](https://user-images.githubusercontent.com/2352663/102339487-82ad3b00-3f95-11eb-9320-8bbfe9c02d65.png)

**Comment by lpatiny** [comment] 2022-02-23 14:39
Here is a dataset:
[data.json.zip](https://github.com/zakodium/react-plot/files/8125103/data.json.zip)

That should yield to something like

![image](https://user-images.githubusercontent.com/1484241/155341165-e4adea9b-5be1-47f3-be84-d6a49c2481c0.png)

**Comment by lpatiny** [comment] 2022-02-23 14:41
@targos Do we agree this issue is a duplicate of https://github.com/zakodium/react-plot/issues/150 ?

**Comment by targos** [comment] 2022-02-23 14:42
I would have done the opposite and closed this issue, as it was initially about customization of scatter series and that has been implemented, but whatever.

**Comment by targos** [comment] 2022-02-24 09:27
We propose the following changes:

- Move `displayMarkers` option from `LineSeriesProps` to `ScatterSeriesProps`. It defaults to `true` in `ScatterSeries` and `false` in `LineSeries`
- Add `lineStyle` and `displayLines` options to `ScatterSeriesProps`. `displayLines` is `false` by default.
  - When `displayLines` is passed, lines will be drawn at each scatter point, interpolating the position between the previous and the next point (see schema below). The default color is the same as the markers.
  - When `lineStyle` is passed, callbacks can be used (for example for the stroke color). The callback is called for each point, like with the markerStyle.
- Add simple stories to show and develop the feature, and then the more complex example from
https://github.com/zakodium/react-plot/issues/50#issuecomment-1048849783

![telegram-cloud-photo-size-4-5818968361915234329-y](https://user-images.githubusercontent.com/2352663/155496491-5cdfc6bb-d128-4432-bdda-41366d8854c2.jpg)

**Comment by targos** [comment] 2022-02-24 09:28
@wadjih-bencheikh18 can you work on this? Don't hesitate to ask here if you need clarifications.

**Comment by wadjih-bencheikh18** [comment] 2022-02-24 14:03
when we use callback for lineStyle
is it supposed to be gradient ?

**Comment by targos** [comment] 2022-02-24 14:05
No, it's supposed to be like the illustration above: small segments of different colors for each point.

**Closed** 2022-02-26 09:01 UTC
Labels: Wadjih
