### ISSUE TITLE
Iris dataset story bug

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium/react-plot#334] opened 2022-02-13 19:58 UTC
https://zakodium.github.io/react-plot/?path=/story/examples-iris-dataset--pca
when we add padding in x Axis the plot will start zoom out

**Comment by targos** [comment] 2022-02-14 05:43
Duplicate of https://github.com/zakodium/react-plot/issues/333

**Closed** 2022-02-14 05:43 UTC
